//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestUserToken.AuthenticationService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
    public partial class IntegrationFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IntegrationFaultCodeType errorTypeField;
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IntegrationFaultCodeType ErrorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
                this.RaisePropertyChanged("ErrorType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("StackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
    public enum IntegrationFaultCodeType {
        
        /// <remarks/>
        General,
        
        /// <remarks/>
        Presentation,
        
        /// <remarks/>
        Network,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Business Rules")]
        BusinessRules,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", ConfigurationName="AuthenticationService.AuthenticationServicePortType")]
    public interface AuthenticationServicePortType {
        
        // CODEGEN: Generating message contract since the operation Login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Login", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestUserToken.AuthenticationService.IntegrationFaultType), Action="urn:Login", Name="IntegrationFault", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestUserToken.AuthenticationService.LoginResponse1 Login(TestUserToken.AuthenticationService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Login", ReplyAction="*")]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.LoginResponse1> LoginAsync(TestUserToken.AuthenticationService.LoginRequest request);
        
        // CODEGEN: Generating message contract since the operation Logout is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestUserToken.AuthenticationService.LogoutResponse1 Logout(TestUserToken.AuthenticationService.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.LogoutResponse1> LogoutAsync(TestUserToken.AuthenticationService.LogoutRequest request);
        
        // CODEGEN: Generating message contract since the operation ReadDatabaseInstances is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReadDatabaseInstances", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestUserToken.AuthenticationService.IntegrationFaultType), Action="urn:ReadDatabaseInstances", Name="IntegrationFault", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestUserToken.AuthenticationService.ReadDatabaseInstancesResponse ReadDatabaseInstances(TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReadDatabaseInstances", ReplyAction="*")]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.ReadDatabaseInstancesResponse> ReadDatabaseInstancesAsync(TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest request);
        
        // CODEGEN: Generating message contract since the operation ReadSessionProperties is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReadSessionProperties", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestUserToken.AuthenticationService.IntegrationFaultType), Action="urn:ReadSessionProperties", Name="IntegrationFault", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestUserToken.AuthenticationService.ReadSessionPropertiesResponse1 ReadSessionProperties(TestUserToken.AuthenticationService.ReadSessionPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReadSessionProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.ReadSessionPropertiesResponse1> ReadSessionPropertiesAsync(TestUserToken.AuthenticationService.ReadSessionPropertiesRequest request);
        
        // CODEGEN: Generating message contract since the operation UpdateSessionProperties is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdateSessionProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse1 UpdateSessionProperties(TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdateSessionProperties", ReplyAction="*")]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse1> UpdateSessionPropertiesAsync(TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class Login : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private int databaseInstanceIdField;
        
        private bool databaseInstanceIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DatabaseInstanceId {
            get {
                return this.databaseInstanceIdField;
            }
            set {
                this.databaseInstanceIdField = value;
                this.RaisePropertyChanged("DatabaseInstanceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatabaseInstanceIdSpecified {
            get {
                return this.databaseInstanceIdFieldSpecified;
            }
            set {
                this.databaseInstanceIdFieldSpecified = value;
                this.RaisePropertyChanged("DatabaseInstanceIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class LoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
                this.RaisePropertyChanged("ReturnSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public TestUserToken.AuthenticationService.Login Login;
        
        public LoginRequest() {
        }
        
        public LoginRequest(TestUserToken.AuthenticationService.Login Login) {
            this.Login = Login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public TestUserToken.AuthenticationService.LoginResponse LoginResponse;
        
        public LoginResponse1() {
        }
        
        public LoginResponse1(TestUserToken.AuthenticationService.LoginResponse LoginResponse) {
            this.LoginResponse = LoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class LogoutResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
                this.RaisePropertyChanged("ReturnSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public object Logout;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(object Logout) {
            this.Logout = Logout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public TestUserToken.AuthenticationService.LogoutResponse LogoutResponse;
        
        public LogoutResponse1() {
        }
        
        public LogoutResponse1(TestUserToken.AuthenticationService.LogoutResponse LogoutResponse) {
            this.LogoutResponse = LogoutResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class ReadDatabaseInstancesResponseDatabaseInstance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int databaseInstanceIdField;
        
        private string databaseEncodingField;
        
        private string databaseNameField;
        
        private DatabaseTypeType databaseTypeField;
        
        private string databaseUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DatabaseInstanceId {
            get {
                return this.databaseInstanceIdField;
            }
            set {
                this.databaseInstanceIdField = value;
                this.RaisePropertyChanged("DatabaseInstanceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DatabaseEncoding {
            get {
                return this.databaseEncodingField;
            }
            set {
                this.databaseEncodingField = value;
                this.RaisePropertyChanged("DatabaseEncoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
                this.RaisePropertyChanged("DatabaseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DatabaseTypeType DatabaseType {
            get {
                return this.databaseTypeField;
            }
            set {
                this.databaseTypeField = value;
                this.RaisePropertyChanged("DatabaseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DatabaseUrl {
            get {
                return this.databaseUrlField;
            }
            set {
                this.databaseUrlField = value;
                this.RaisePropertyChanged("DatabaseUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public enum DatabaseTypeType {
        
        /// <remarks/>
        Oracle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SQL Server")]
        SQLServer,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadDatabaseInstancesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public object ReadDatabaseInstances;
        
        public ReadDatabaseInstancesRequest() {
        }
        
        public ReadDatabaseInstancesRequest(object ReadDatabaseInstances) {
            this.ReadDatabaseInstances = ReadDatabaseInstances;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadDatabaseInstancesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadDatabaseInstancesResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DatabaseInstance", IsNullable=false)]
        public TestUserToken.AuthenticationService.ReadDatabaseInstancesResponseDatabaseInstance[] ReadDatabaseInstancesResponse1;
        
        public ReadDatabaseInstancesResponse() {
        }
        
        public ReadDatabaseInstancesResponse(TestUserToken.AuthenticationService.ReadDatabaseInstancesResponseDatabaseInstance[] ReadDatabaseInstancesResponse1) {
            this.ReadDatabaseInstancesResponse1 = ReadDatabaseInstancesResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class ReadSessionPropertiesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isValidField;
        
        private int userObjectIdField;
        
        private string userNameField;
        
        private int databaseInstanceIdField;
        
        private string databaseEncodingField;
        
        private string databaseNameField;
        
        private DatabaseTypeType databaseTypeField;
        
        private string databaseUrlField;
        
        private bool ignoreNullComplexFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("IsValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserObjectId {
            get {
                return this.userObjectIdField;
            }
            set {
                this.userObjectIdField = value;
                this.RaisePropertyChanged("UserObjectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DatabaseInstanceId {
            get {
                return this.databaseInstanceIdField;
            }
            set {
                this.databaseInstanceIdField = value;
                this.RaisePropertyChanged("DatabaseInstanceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DatabaseEncoding {
            get {
                return this.databaseEncodingField;
            }
            set {
                this.databaseEncodingField = value;
                this.RaisePropertyChanged("DatabaseEncoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
                this.RaisePropertyChanged("DatabaseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DatabaseTypeType DatabaseType {
            get {
                return this.databaseTypeField;
            }
            set {
                this.databaseTypeField = value;
                this.RaisePropertyChanged("DatabaseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DatabaseUrl {
            get {
                return this.databaseUrlField;
            }
            set {
                this.databaseUrlField = value;
                this.RaisePropertyChanged("DatabaseUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IgnoreNullComplexFields {
            get {
                return this.ignoreNullComplexFieldsField;
            }
            set {
                this.ignoreNullComplexFieldsField = value;
                this.RaisePropertyChanged("IgnoreNullComplexFields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadSessionPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public object ReadSessionProperties;
        
        public ReadSessionPropertiesRequest() {
        }
        
        public ReadSessionPropertiesRequest(object ReadSessionProperties) {
            this.ReadSessionProperties = ReadSessionProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadSessionPropertiesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public TestUserToken.AuthenticationService.ReadSessionPropertiesResponse ReadSessionPropertiesResponse;
        
        public ReadSessionPropertiesResponse1() {
        }
        
        public ReadSessionPropertiesResponse1(TestUserToken.AuthenticationService.ReadSessionPropertiesResponse ReadSessionPropertiesResponse) {
            this.ReadSessionPropertiesResponse = ReadSessionPropertiesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class UpdateSessionProperties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool ignoreNullComplexFieldsField;
        
        private bool ignoreNullComplexFieldsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IgnoreNullComplexFields {
            get {
                return this.ignoreNullComplexFieldsField;
            }
            set {
                this.ignoreNullComplexFieldsField = value;
                this.RaisePropertyChanged("IgnoreNullComplexFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IgnoreNullComplexFieldsSpecified {
            get {
                return this.ignoreNullComplexFieldsFieldSpecified;
            }
            set {
                this.ignoreNullComplexFieldsFieldSpecified = value;
                this.RaisePropertyChanged("IgnoreNullComplexFieldsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class UpdateSessionPropertiesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
                this.RaisePropertyChanged("ReturnSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSessionPropertiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public TestUserToken.AuthenticationService.UpdateSessionProperties UpdateSessionProperties;
        
        public UpdateSessionPropertiesRequest() {
        }
        
        public UpdateSessionPropertiesRequest(TestUserToken.AuthenticationService.UpdateSessionProperties UpdateSessionProperties) {
            this.UpdateSessionProperties = UpdateSessionProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSessionPropertiesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse UpdateSessionPropertiesResponse;
        
        public UpdateSessionPropertiesResponse1() {
        }
        
        public UpdateSessionPropertiesResponse1(TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse UpdateSessionPropertiesResponse) {
            this.UpdateSessionPropertiesResponse = UpdateSessionPropertiesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationServicePortTypeChannel : TestUserToken.AuthenticationService.AuthenticationServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServicePortTypeClient : System.ServiceModel.ClientBase<TestUserToken.AuthenticationService.AuthenticationServicePortType>, TestUserToken.AuthenticationService.AuthenticationServicePortType {
        
        public AuthenticationServicePortTypeClient() {
        }
        
        public AuthenticationServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestUserToken.AuthenticationService.LoginResponse1 TestUserToken.AuthenticationService.AuthenticationServicePortType.Login(TestUserToken.AuthenticationService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public TestUserToken.AuthenticationService.LoginResponse Login(TestUserToken.AuthenticationService.Login Login1) {
            TestUserToken.AuthenticationService.LoginRequest inValue = new TestUserToken.AuthenticationService.LoginRequest();
            inValue.Login = Login1;
            TestUserToken.AuthenticationService.LoginResponse1 retVal = ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).Login(inValue);
            return retVal.LoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.LoginResponse1> TestUserToken.AuthenticationService.AuthenticationServicePortType.LoginAsync(TestUserToken.AuthenticationService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestUserToken.AuthenticationService.LoginResponse1> LoginAsync(TestUserToken.AuthenticationService.Login Login) {
            TestUserToken.AuthenticationService.LoginRequest inValue = new TestUserToken.AuthenticationService.LoginRequest();
            inValue.Login = Login;
            return ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestUserToken.AuthenticationService.LogoutResponse1 TestUserToken.AuthenticationService.AuthenticationServicePortType.Logout(TestUserToken.AuthenticationService.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public TestUserToken.AuthenticationService.LogoutResponse Logout(object Logout1) {
            TestUserToken.AuthenticationService.LogoutRequest inValue = new TestUserToken.AuthenticationService.LogoutRequest();
            inValue.Logout = Logout1;
            TestUserToken.AuthenticationService.LogoutResponse1 retVal = ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).Logout(inValue);
            return retVal.LogoutResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.LogoutResponse1> TestUserToken.AuthenticationService.AuthenticationServicePortType.LogoutAsync(TestUserToken.AuthenticationService.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestUserToken.AuthenticationService.LogoutResponse1> LogoutAsync(object Logout) {
            TestUserToken.AuthenticationService.LogoutRequest inValue = new TestUserToken.AuthenticationService.LogoutRequest();
            inValue.Logout = Logout;
            return ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestUserToken.AuthenticationService.ReadDatabaseInstancesResponse TestUserToken.AuthenticationService.AuthenticationServicePortType.ReadDatabaseInstances(TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest request) {
            return base.Channel.ReadDatabaseInstances(request);
        }
        
        public TestUserToken.AuthenticationService.ReadDatabaseInstancesResponseDatabaseInstance[] ReadDatabaseInstances(object ReadDatabaseInstances1) {
            TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest inValue = new TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest();
            inValue.ReadDatabaseInstances = ReadDatabaseInstances1;
            TestUserToken.AuthenticationService.ReadDatabaseInstancesResponse retVal = ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).ReadDatabaseInstances(inValue);
            return retVal.ReadDatabaseInstancesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.ReadDatabaseInstancesResponse> TestUserToken.AuthenticationService.AuthenticationServicePortType.ReadDatabaseInstancesAsync(TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest request) {
            return base.Channel.ReadDatabaseInstancesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestUserToken.AuthenticationService.ReadDatabaseInstancesResponse> ReadDatabaseInstancesAsync(object ReadDatabaseInstances) {
            TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest inValue = new TestUserToken.AuthenticationService.ReadDatabaseInstancesRequest();
            inValue.ReadDatabaseInstances = ReadDatabaseInstances;
            return ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).ReadDatabaseInstancesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestUserToken.AuthenticationService.ReadSessionPropertiesResponse1 TestUserToken.AuthenticationService.AuthenticationServicePortType.ReadSessionProperties(TestUserToken.AuthenticationService.ReadSessionPropertiesRequest request) {
            return base.Channel.ReadSessionProperties(request);
        }
        
        public TestUserToken.AuthenticationService.ReadSessionPropertiesResponse ReadSessionProperties(object ReadSessionProperties1) {
            TestUserToken.AuthenticationService.ReadSessionPropertiesRequest inValue = new TestUserToken.AuthenticationService.ReadSessionPropertiesRequest();
            inValue.ReadSessionProperties = ReadSessionProperties1;
            TestUserToken.AuthenticationService.ReadSessionPropertiesResponse1 retVal = ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).ReadSessionProperties(inValue);
            return retVal.ReadSessionPropertiesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.ReadSessionPropertiesResponse1> TestUserToken.AuthenticationService.AuthenticationServicePortType.ReadSessionPropertiesAsync(TestUserToken.AuthenticationService.ReadSessionPropertiesRequest request) {
            return base.Channel.ReadSessionPropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestUserToken.AuthenticationService.ReadSessionPropertiesResponse1> ReadSessionPropertiesAsync(object ReadSessionProperties) {
            TestUserToken.AuthenticationService.ReadSessionPropertiesRequest inValue = new TestUserToken.AuthenticationService.ReadSessionPropertiesRequest();
            inValue.ReadSessionProperties = ReadSessionProperties;
            return ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).ReadSessionPropertiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse1 TestUserToken.AuthenticationService.AuthenticationServicePortType.UpdateSessionProperties(TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest request) {
            return base.Channel.UpdateSessionProperties(request);
        }
        
        public TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse UpdateSessionProperties(TestUserToken.AuthenticationService.UpdateSessionProperties UpdateSessionProperties1) {
            TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest inValue = new TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest();
            inValue.UpdateSessionProperties = UpdateSessionProperties1;
            TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse1 retVal = ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).UpdateSessionProperties(inValue);
            return retVal.UpdateSessionPropertiesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse1> TestUserToken.AuthenticationService.AuthenticationServicePortType.UpdateSessionPropertiesAsync(TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest request) {
            return base.Channel.UpdateSessionPropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestUserToken.AuthenticationService.UpdateSessionPropertiesResponse1> UpdateSessionPropertiesAsync(TestUserToken.AuthenticationService.UpdateSessionProperties UpdateSessionProperties) {
            TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest inValue = new TestUserToken.AuthenticationService.UpdateSessionPropertiesRequest();
            inValue.UpdateSessionProperties = UpdateSessionProperties;
            return ((TestUserToken.AuthenticationService.AuthenticationServicePortType)(this)).UpdateSessionPropertiesAsync(inValue);
        }
    }
}
